services:
  jenkins:
    image: jenkins/jenkins:lts-alpine
    container_name: jenkins
    environment:
      - JAVA_OPTS=-Xmx256m -XX:MaxRAM=512m
      - JENKINS_OPTS=--httpPort=8080
    volumes:
      - jenkins_home:/var/jenkins_home
      - /home/6ckys/6ckys-laravel-project:/var/laravel-project
      - ./scripts:/var/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    restart: unless-stopped
    mem_limit: 512m
    memswap_limit: 512m
    user: root
    command: |
      bash -c "
        # Install dependencies
        apk add --no-cache curl git bash libc6-compat shadow && \
        # Install Docker CLI
        mkdir -p /tmp/download && \
        curl -fsSL https://download.docker.com/linux/static/stable/$$(uname -m | sed 's/aarch64/arm64/;s/x86_64/x86_64/')/docker-28.0.4.tgz | tar -xz -C /tmp/download && \
        mv /tmp/download/docker/docker /usr/bin/ && \
        rm -rf /tmp/download && \
        # Install Docker Compose v2
        mkdir -p /usr/local/lib/docker/cli-plugins && \
        curl -fsSL https://github.com/docker/compose/releases/download/v2.34.0/docker-compose-linux-$$(uname -m | sed 's/aarch64/arm64/;s/x86_64/x86_64/') -o /usr/local/lib/docker/cli-plugins/docker-compose && \
        chmod +x /usr/local/lib/docker/cli-plugins/docker-compose && \
        # Setup permissions
        groupadd -g 998 docker && \
        usermod -aG docker jenkins && \
        git config --system --add safe.directory '*'
        /sbin/tini -- /usr/local/bin/jenkins.sh
      "

volumes:
  jenkins_home: